@url = {{host}}/auth

### GET test endpoint requiring authorization
# @no-cookie-jar
< {%
    const token = client.global.get("token")
    request.variables.set("token", token)
%}
GET {{url}}/secret
Authorization: Bearer {{token}}

### GET test endpoint with failing token
GET {{url}}/secret
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJaaWVKcGJFZzFOQGphQ1p6Si5jeiIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpYXQiOjE3NDQyMjc3NTgsImV4cCI6MTc0NDIzMTM1OH0.Mm3ZWphjsZ74g1Igt3JfIDz9ako3n-q3ExNZ78_prD0