@url = {{host}}/auth

### LOGIN with recently created user account
< {%
    const email = client.global.get("email")
    request.variables.set("email", client.global.get("email"))
%}
POST {{url}}/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "pa$$w0RD"
}

> {%
    const token = response.body.token
    const refreshToken = response.body.refreshToken
    client.global.set("token", token)
    client.global.set("refreshToken", refreshToken)
%}

### REFRESH JWT token
< {%
    const refreshToken = client.global.get("refreshToken")
    request.variables.set("refreshToken", refreshToken)
%}
GET {{url}}/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

> {%
    const token = response.body.token
    client.global.set("token", token)
%}
