@url = {{host}}/user

### POST new random USER without company name
< {%
    const email = $random.email
    client.global.set("email", email)
    request.variables.set("email", email)
%}
POST {{url}}
Content-Type: application/json

{
  "firstName": "{{$random.address.firstName}}",
  "lastName": "{{$random.address.lastName}}",
  "email": "{{email}}",
  "password": "pa$$w0RD",
  "roleName": "ROLE_USER"
}

### POST new random USER with company name
POST {{url}}
Content-Type: application/json

{
  "firstName": "{{$random.address.firstName}}",
  "lastName": "{{$random.address.lastName}}",
  "email": "{{$random.email}}",
  "password": "pa$$w0RD",
  "roleName": "ROLE_USER",
  "companyName": "{{$random.company.name}}"
}

### POST new random ADMIN
< {%
    const email = $random.email
    client.global.set("email", email)
    request.variables.set("email", email)
    const token = client.global.get("token")
    request.variables.set("token", token)
%}
POST {{url}}/admin
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "firstName": "{{$random.address.firstName}}",
  "lastName": "{{$random.address.lastName}}",
  "email": "{{email}}",
  "password": "pa$$w0RD",
  "roleName": "ROLE_ADMIN"
}

### POST new random SUPER_ADMIN
< {%
    const email = $random.email
    client.global.set("email", email)
    request.variables.set("email", email)
    const token = client.global.get("token")
    request.variables.set("token", token)
%}
POST {{url}}/super-admin
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "firstName": "{{$random.address.firstName}}",
  "lastName": "{{$random.address.lastName}}",
  "email": "{{$random.email}}",
  "password": "pa$$w0RD",
  "roleName": "ROLE_SUPER_ADMIN"
}

### GET user by ID
GET {{url}}/3

### UPDATE user by ID with data in body
PUT {{url}}/3
Content-Type: application/json

{
  "firstName": "{{$random.address.firstName}}",
  "lastName": "{{$random.address.lastName}}",
  "email": "{{$random.email}}",
  "companyName": "{{$random.company.name}}",
  "roleName": "ROLE_SUPER_ADMIN"
}

### UPDATE user password
PUT {{url}}/33/password
Content-Type: application/json

{
  "password": "pa$$w0RD2"
}

### DELETE user by ID (ADMIN)
< {%
    const token = client.global.get("token")
    request.variables.set("token", token)
%}
DELETE {{url}}/admin/16
Authorization: Bearer {{token}}

### DELETE user by ID (SUPER_ADMIN)
< {%
    const token = client.global.get("token")
    request.variables.set("token", token)
%}
DELETE {{url}}/super-admin/16
Authorization: Bearer {{token}}

### GET current user data
# @no-cookie-jar
< {%
    const token = client.global.get("token")
    request.variables.set("token", token)
%}
GET {{url}}/me
Authorization: Bearer {{token}}
